// Do not edit. This file is machine generated by the Resource DLL Wizard.

library CEMM;

{ITE} {DFMFileType} {C\Users\sfajardo\Documents\Embarcadero\Studio\Projects\CEMM\Conan-Exiles-Mod-Manager\CEMM\MainUnit.dfm}
{ITE} {RCFileType} {C\Users\sfajardo\Documents\Embarcadero\Studio\Projects\CEMM\Conan-Exiles-Mod-Manager\CEMM\Win32\Debug\CEMM_DRC.rc}

{$R 'C\Users\sfajardo\Documents\Embarcadero\Studio\Projects\CEMM\Conan-Exiles-Mod-Manager\CEMM\MainUnit.dfm' 'Form1:TForm'}
{$R 'C\Users\sfajardo\Documents\Embarcadero\Studio\Projects\CEMM\Conan-Exiles-Mod-Manager\CEMM\Win32\Debug\CEMM_DRC.res' 'C\Users\sfajardo\Documents\Embarcadero\Studio\Projects\CEMM\Conan-Exiles-Mod-Manager\CEMM\Win32\Debug\CEMM_DRC.rc'}

{$E DEU}

begin
end.
